security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: https://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    prefer-ip-address: false
    hostname: account-service

spring:
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
    rabbitmq:
      ssl:
        enabled: true
        algorithm: TLSv1.2
        key-store: classpath:client_rabbitmq_key.p12
        key-store-password: piggymetrics
        key-store-type: PKCS12
        key-alias: client
        key-password: piggymetrics
        trust-store: classpath:ca_certificate.p12
        trust-store-password: piggymetrics
        trust-store-type: PKCS12

server:
  servlet:
    context-path: /accounts
  ssl:
    enabled: true
    key-store: classpath:account.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: account
    key-password: password
  port: 6000

feign:
  hystrix:
    enabled: true