spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  rabbitmq:
    ssl:
      enabled: true
      algorithm: TLSv1.2
      key-store: classpath:client_rabbitmq_key.p12
      key-store-password: piggymetrics
      key-store-type: PKCS12
      key-alias: client
      key-password: piggymetrics
      trust-store: classpath:ca_certificate.p12
      trust-store-password: piggymetrics
      trust-store-type: PKCS12

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    prefer-ip-address: false
    hostname: auth-service

server:
  servlet:
    context-path: /uaa
  ssl:
    enabled: true
    key-store: classpath:auth.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: auth
    key-password: password
  port: 5000
