hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  rabbitmq:
    ssl:
      enabled: true
      algorithm: TLSv1.2
      key-store: classpath:client_rabbitmq_key.p12
      key-store-password: piggymetrics
      key-store-type: PKCS12
      key-alias: client
      key-password: piggymetrics
      trust-store: classpath:ca_certificate.p12
      trust-store-password: piggymetrics
      trust-store-type: PKCS12

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /uaa/**
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:

    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:

    statistics-service:
        path: /statistics/**
        serviceId: statistics-service
        stripPrefix: false
        sensitiveHeaders:

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:

server:
  ssl:
    enabled: true
    key-store: classpath:gateway.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: gateway
    key-password: password
  port: 4000
