spring:
  rabbitmq:
    ssl:
      enabled: true
      algorithm: TLSv1.2
      key-store: classpath:client_rabbitmq_key.p12
      key-store-password: piggymetrics
      key-store-type: PKCS12
      key-alias: client
      key-password: piggymetrics
      trust-store: classpath:ca_certificate.p12
      trust-store-password: piggymetrics
      trust-store-type: PKCS12

server:
  ssl:
    enabled: true
    key-store: classpath:registry.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: registry
    key-password: password
  port: 8761