security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: statistics-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  rabbitmq:
    ssl:
      enabled: true
      algorithm: TLSv1.2
      key-store: classpath:client_rabbitmq_key.p12
      key-store-password: piggymetrics
      key-store-type: PKCS12
      key-alias: client
      key-password: piggymetrics
      trust-store: classpath:ca_certificate.p12
      trust-store-password: piggymetrics
      trust-store-type: PKCS12

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io